namespace SmartHome.Api.Services.Chat;

/// <summary>
/// Defines a service for interacting with a language model to generate responses
/// based on user-provided messages.
/// </summary>
public interface ILlmChatService
{
    /// <summary>
    /// Sends a message to the language model and returns the generated response.
    /// </summary>
    /// <param name="message">The user message to process.</param>
    /// <param name="cancellationToken">A token used to cancel the operation.</param>
    /// <returns>The response generated by the language model.</returns>
    Task<string> GetResponseAsync(string message, CancellationToken cancellationToken = default);
}