// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Infrastructure.Persistence;

#nullable disable

namespace SmartHome.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20260422022527_RestoreIntermediateDevices")]
    partial class RestoreIntermediateDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SmartHome.Domain.Device.CommandHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceHistory");
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Device", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartHome.Domain.Device.DoorLock.DoorLock", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("LockState")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.PoweredDevice", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("PowerState")
                        .HasColumnType("INTEGER");
                });

            modelBuilder.Entity("SmartHome.Domain.Device.TickableDevice", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Fan.Fan", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.PoweredDevice");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Light.Light", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.PoweredDevice");

                    b.Property<int>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Thermostat.Thermostat", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.TickableDevice");

                    b.Property<int>("AmbientTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesiredTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);
                });
#pragma warning restore 612, 618
        }
    }
}
