// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Infrastructure.Persistence;

#nullable disable

namespace SmartHome.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20260417195511_FixDeviceInheritance")]
    partial class FixDeviceInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SmartHome.Domain.Device.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartHome.Domain.Device.DoorLock", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("LockState")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Fan", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("PowerState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Light", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Thermostat", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Device.Device");

                    b.Property<int>("AmbientTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesiredTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);
                });
#pragma warning restore 612, 618
        }
    }
}
